language: php
php:
  - 5.4
  - 5.5
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=3.9 WP_MULTISITE=0
before_script:
  - composer install --dev
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit --tap --coverage-clover build/logs/clover.xml
after_script:
  - bash bin/code-climate-coverage.sh
